### ISSUE TITLE
Cannot process files if recursive is on

### ISSUE THREAD

**Issue by applewiskey** [danfruehauf/incron#2]
Hi.

I'm using incrond with recursive watch, but want to use it with files as well.
When I'm trying to use it with files I have the following error:

```
could not open directory /var/lib/puppet/ssl/ca/ca_crl.pem: Not a directory
```

**Comment by danfruehauf** [comment]
I should have a look into that. I just recently added this feature. Do you have an example of how to reproduce this?

I just had another look in the code and it is testing to see whether a newly added entry is a directory or not:
https://github.com/danfruehauf/incron/blob/master/usertable.cpp#L286

**Comment by applewiskey** [comment]
```
# ps axu | grep incron
root     17766  0.0  0.0  15316  1548 ?        Ss   16:19   0:00 /usr/sbin/incrond -r
```

Recursive config:

```
# mkdir /tmp/itest/
# cat /etc/incron.d/test
/tmp/itest/ IN_CREATE /tmp/test.sh
```

Result:

```
incrond[17766]: (system::test) CMD (/tmp/test.sh)
```

Single file config:

```
touch /tmp/itest/1
/tmp/itest/1 IN_MODIFY /tmp/test.sh
```

Result:

```
incrond[23953]: could not open directory /tmp/itest/1: Not a directory
```

**Comment by applewiskey** [comment]
So you just basically looking for file and directory while -r option enabled.
I'm build incrond with systemd support.
My systemd service file (from CentOS 0.5.10 ver):

```
[Unit]
Description=Inotify System Scheduler

[Service]
Type=forking
PIDFile=/run/incrond.pid
ExecStart=/usr/sbin/incrond -r

[Install]
WantedBy=multi-user.target
```

**Comment by danfruehauf** [comment]
@applewiskey I think #3 will solve it. Please give it a go. I couldn't quite reproduce your problem but I think I understood what you were trying to do.

**Comment by applewiskey** [comment]
Sorry for such a long delay.
It works with patch you provided.

**Comment by danfruehauf** [comment]
No worries. Happy times. 👍
